apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  namespace: redis
  labels:
    app.kubernetes.io/name: redis
    app: redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mnt/data/persistence/redis
    type: DirectoryOrCreate
