alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app: alertmanager

grafana:
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.230
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.1.222
      traefik.ingress.kubernetes.io/router.entrypoints: local
    hosts:
      - grafana.local.boomerok.dev
    tls:
      - secretName: local-tls
        hosts:
          - grafana.local.boomerok.dev
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://grafana-loki.observability:3100/

prometheus:
  prometheusSpec:
#    securityContext:
#      runAsGroup: 0
#      runAsNonRoot: false
#      runAsUser: 0
#      fsGroup: 2000
#      seccompProfile:
#        type: RuntimeDefault
    logLevel: debug
#    volumes:
#      - name: prometheus-hostpath-pvc
#        persistentVolumeClaim:
#          claimName: prometheus-hostpath-pvc
#      - name: prometheus-xfs
#        hostPath:
#          path: /var/disk/a/data/observability/prometheus2
#          type: DirectoryOrCreate
#      - name: prometheus-zfs
#        hostPath:
#          path: /var/mnt/data/persistence/observability/prometheus
#          type: DirectoryOrCreate
#    volumeMounts:
#      - mountPath: /prometheus-hostpath
#        name: prometheus-hostpath-pvc
#      - mountPath: /prometheus-os
#        name: prometheus-kube-prometheus-stack-prometheus-db
##        subPath: prometheus-db
#      - mountPath: /prometheus-xfs
#        name: prometheus-xfs
#      - mountPath: /prometheus-zfs
#        name: prometheus-zfs
    storageSpec:
      volumeClaimTemplate:
        spec:
#          storageClassName: openebs-hostpath
          storageClassName:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app: prometheus-zfs
