apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
  - volumes
configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: observability
    files:
      - values.yaml=kube-prometheus-stack-values.yaml
configurations:
  - ../kustomizeconfig.yaml
