global:
  addPrometheusAnnotations: true
  annotations:
    sidecar.cilium.io/inject: 'true'
  additionalLabels:
    app: authentik
  env:
    - name: AUTHENTIK_TRUST_PROXY_HEADERS
      value: 'true'
  envFrom:
    - secretRef:
        name: authentik-secrets
  volumeMounts:
    - mountPath: /media
      name: media
  volumes:
    - name: media
      hostPath:
        path: /var/openebs/local/data/authentik
        type: DirectoryOrCreate

authentik:
  postgresql:
    host: postgres-service.postgres.svc.cluster.local
  redis:
    host: redis-master.redis.svc.cluster.local
    db: '5'

server:
  metrics:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - authentik.boomerok.dev
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.boomerok.dev
    https: false
