global:
  addPrometheusAnnotations: true
  additionalLabels:
    app: authentik
  envFrom:
    - secretRef:
        name: authentik-secrets


authentik:
  postgresql:
    host: postgres-service.postgres.svc.cluster.local
  redis:
    host: redis-master.redis.svc.cluster.local
    db: '5'

server:
  metrics:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - authentik.boomerok.dev
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.boomerok.dev
    https: false
