authentik:
  secret_key: 'eD5TVq2/6atOkNR8md2ktNKRqtR8nESgDOhZpzFKJ2QJn6IDaHmx9D73oSiGLRNhARk0LsWMdRcoBJzp'

  postgresql:
    host: postgres-service
    password: 'OYcmI^%@EDhzJX83'

server:
  ingress:
    enabled: true
    hosts:
      - authentik.domain.tld

redis:
  enabled: true

global:
  addPrometheusAnnotations: true
