apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: authentik-secrets
    envs:
      - authentik-secrets.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: authentik-values
    namespace: authentik
    files:
      - values.yaml=authentik-values.yaml
configurations:
  - kustomizeconfig.yaml
