apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.8.222
    traefik.ingress.kubernetes.io/router.entrypoints: local
spec:
  rules:
    - host: homepage.local.boomerok.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homepage-service
                port:
                  name: http
  tls:
    - secretName: local-tls
      hosts:
        - homepage.local.boomerok.dev
