nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/template/spec/volumes/configMap/name
        kind: Deployment
      - path: spec/template/spec/containers/envFrom/secretRef/name
