apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-role.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    files:
      - config/settings.yaml
      - config/services.yaml
      - config/widgets.yaml
      - config/kubernetes.yaml
      - config/bookmarks.yaml
    options:
      labels:
        app.kubernetes.io/name: homepage
secretGenerator:
  - name: homepage-secrets
    namespace: homepage
    envs:
      - config/secrets.env
    options:
      labels:
        app.kubernetes.io/name: homepage
configurations:
  - kustomizeconfig.yaml
