apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - cluster-role.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: homepage-config
    namespace: homepage
    files:
      - settings.yaml
      - services.yaml
      - widgets.yaml
      - kubernetes.yaml
    options:
      labels:
        app.kubernetes.io/name: homepage
configurations:
  - kustomizeconfig.yaml
