clusterName: perpetulab-cluster

talosVersion: v1.7.4
kubernetesVersion: v1.30.1

endpoint: https://192.168.1.4:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - boomerok.dev
additionalApiServerCertSans:
  - boomerok.dev
cniConfig:
  name: none

patches:
  - |-
    cluster:
      proxy:
        disabled: true

nodes:
  - hostname: homeserver
    ipAddress: 192.168.1.4
    talosImageURL: ghcr.io/siderolabs/installer
    installDiskSelector:
      size: '< 65GB'
      model: 'SanDisk 3.2Gen1'
    controlPlane: true
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
    machineDisks:
      - device: /dev/disk/by-id/ata-CT2000MX500SSD1_2405E895C800
        partitions:
          - mountpoint: /var/openebs/local
    patches:
      - |-
        machine:
          kubelet:
            extraConfig:
               serverTLSBootstrap: true            
            extraArgs:
              rotate-server-certificates: true
            extraMounts:
              - destination: /var/openebs/local
                type: bind
                source: /var/openebs/local
                options:
                  - bind
                  - rshared
                  - rw
