apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/marcin795/processing-frontend:latest
          ports:
            - containerPort: 8000
              name: frontend
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbit-credentials
