apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-ui
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-ui
  template:
    metadata:
      labels:
        app: ingest-ui
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ingest-ui
          image: ghcr.io/marcin795/ingest:latest
          imagePullPolicy: Always
