apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: processing
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.8.222
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: processing-frontend.boomerok.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  name: frontend
  tls:
    - secretName: frontend-tls
      hosts:
        - processing-frontend.boomerok.dev
