apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: processing
  labels:
    app.kubernetes.io/name: frontend
    app: frontend
spec:
  ports:
    - port: 8000
      targetPort: frontend
      name: frontend
  selector:
    app.kubernetes.io/name: frontend
    app: frontend
