apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: observability
  labels:
    app: alertmanager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/alertmanager
    type: DirectoryOrCreate
