apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/grafana
    type: DirectoryOrCreate
