apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: observability
  labels:
    app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mnt/data/persistence/observability/prometheus
    type: DirectoryOrCreate
