apiVersion: apps/v1
kind: Deployment
metadata:
  name: shitscreen
  namespace: shitscreen
spec:
  selector:
    matchLabels:
      app: shitscreen
  replicas: 1
  template:
    metadata:
      labels:
        app: shitscreen
    spec:
      shareProcessNamespace: true
      containers:
        - name: mitmproxy
          tty: true
          args:
            - mitmweb
            - --web-host
            - 0.0.0.0
          image: mitmproxy/mitmproxy
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: mitmproxy-config
              mountPath: /home/mitmproxy/.mitmproxy/config.yaml
              subPath: config.yaml
            - name: mitmproxy
              mountPath: /home/mitmproxy/.mitmproxy
              subPath: .mitmproxy
            - name: mitmproxy-addons
              mountPath: /home/mitmproxy/addons
            - name: node
              mountPath: /socket
              subPath: socket
        - name: node
          command:
            - tail
            - -f
            - /dev/null
#            - node
#            - /node/server.js
          image: ghcr.io/marcin795/shitscreen:latest
          volumeMounts:
            - mountPath: /node
              name: node
            - mountPath: /node/app
              name: node-scripts
      volumes:
        - name: mitmproxy-addons
          configMap:
            name: mitmproxy-addons
        - name: node-scripts
          configMap:
            name: node-scripts
        - name: mitmproxy-config
          configMap:
            name: mitmproxy-config
        - name: mitmproxy
          hostPath:
            path: /var/openebs/local/mitmproxy
            type: DirectoryOrCreate
        - name: node
          hostPath:
            path: /var/openebs/local/node
            type: DirectoryOrCreate
