apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: mitmproxy-config
    namespace: shitscreen
    files:
      - config.yaml
configurations:
  - kustomizeconfig.yaml
