apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
  namespace: shitscreen
  labels:
    app: mitmproxy
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.203
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: proxy
    - port: 8081
      targetPort: 8081
      name: web
  selector:
    app: mitmproxy
  type: LoadBalancer
