apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localpv-vol
  namespace: pvc-test
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      #Set capacity here
      storage: 5Gi
