apiVersion: v1
kind: Pod
metadata:
  name: recyclarr
  namespace: arr
spec:
  containers:
    - name: recyclarr
      image: ghcr.io/recyclarr/recyclarr:7.4.0
      env:
        - name: TZ
          value: Europe/Warsaw
      volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/configs/radarr.yaml
          name: radarr-config
          subPath: radarr.yaml
        - mountPath: /config/secrets.yaml
          name: recyclarr-secrets
          subPath: secrets.yaml
  volumes:
    - name: config
      hostPath:
        path: /var/data/persistence/arr/recyclarr
        type: DirectoryOrCreate
    - name: radarr-config
      configMap:
        name: radarr-config
    - name: recyclarr-secrets
      secret:
        secretName: recyclarr-secrets
  restartPolicy: OnFailure
