#alertmanager:
#  alertmanagerSpec:
#    storage:
#      volumeClaimTemplate:
#        spec:
#          accessModes: ["ReadWriteOnce"]
#          selector:
#            matchLabels:
#              app: alertmanager

grafana:
  persistence:
    enabled: true
    existingClaim: grafana-pvc

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          selector:
            matchLabels:
              app: prometheus
