apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch
  namespace: zfs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scratch
      app: scratch
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scratch
        app: scratch
    spec:
      containers:
        - name: scratch
          image: alpine
          command:
            - apk add zfs && \
            - apk add curl && \
            - apk add git && \
            - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
            - tail -f /dev/null
          volumeMounts:
            - mountPath: /data
              name: zfs
      volumes:
        - name: zfs
          hostPath:
            path: /var/mnt/data
