apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scratch
      app: scratch
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scratch
        app: scratch
    spec:
      containers:
        - name: scratch
#          image: alpine
          image: quay.io/prometheus/prometheus:v3.0.1
          command:
            - tail
            - -f
            - /dev/null
          volumeMounts:
            - name: openebs-pvc
              mountPath: /openebs-pvc
            - mountPath: /data
              name: zfs
            - mountPath: /prometheus
              name: prometheus
#          securityContext:
#            runAsUser: 1000
#            runAsGroup: 2000
      volumes:
        - name: openebs-pvc
          persistentVolumeClaim:
            claimName: prometheus-hostpath-pvc
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
        - name: zfs
          hostPath:
            path: /var/mnt/data
