apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch
  namespace: zfs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scratch
      app: scratch
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scratch
        app: scratch
    spec:
      containers:
        - name: scratch
          image: alpine
          command:
            - tail
            - -f
            - /dev/null
          volumeMounts:
            - mountPath: /data
              name: zfs
            - mountPath: /prometheus
              name: prometheus
      volumes:
        - name: prometheus
          persistentVolumeClaim:
            claimName: prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0
        - name: zfs
          hostPath:
            path: /var/mnt/data
