apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent:5.0.3-r0-ls379
          ports:
            - name: qbittorrent-web
              containerPort: 8080
            - name: qbittorrent-torrent
              containerPort: 18863
          env:
            - name: TZ
              value: Europe/Warsaw
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: TORRENTING_PORT
              value: '18863'
            - name: DOCKER_MODS
              value: ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads
              name: downloads
            - mountPath: /vuetorrent
              name: vuetorrent
      volumes:
        - name: config
          hostPath:
            path: /var/mnt/data/persistence/arr/qbittorrent/config
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /var/storage/media/downloads
            type: DirectoryOrCreate
        - name: vuetorrent
          hostPath:
            path: /var/mnt/data/persistence/arr/qbittorrent/vuetorrent
            type: DirectoryOrCreate
