apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-test
  namespace: arr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-test
      app: qbittorrent-test
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent-test
        app: qbittorrent-test
    spec:
      containers:
        - name: python
          image: python
      initContainers:
        - name: dnsdist
          image: docker.io/powerdns/dnsdist-19:1.9.8
          restartPolicy: Always
          command:
            - tail
            - -f
            - /dev/null
          volumeMounts:
            - name: dnsdist
              mountPath: /etc/dnsdist/dnsdist.conf
              subPath: dnsdist.conf
        - name: gluetun
          image: qmcgaw/gluetun:v3.40.0
          restartPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp /gluetun/auth/config-template.toml /gluetun/auth/config.toml;
                    sed -i "s|__API_KEY__|${GSP_GTN_API_KEY}|g" /gluetun/auth/config.toml;
                    (ip rule del table 51820; ip -6 rule del table 51820) || true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            ###################### REQUIRED ######################
            - name: DOT
              value: "off"
            - name: DNS_ADDRESS
              value: 127.0.0.2
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: wireguard
            - name: VPN_PORT_FORWARDING
              value: 'on'
            - name: PORT_FORWARD_ONLY
              value: 'on'
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: protonvpn
            - name: FIREWALL_INPUT_PORTS
              value: '8080'
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: 10.244.0.0/16,10.96.0.0/12
            - name: FIREWALL_DEBUG
              value: 'on'
            - name: SERVER_COUNTRIES
              value: Poland
            - name: WIREGUARD_ENDPOINT_IP
              value: 146.70.161.162
            - name: WIREGUARD_ADDRESSES
              value: 10.2.0.2/32
          envFrom:
            - secretRef:
                name: wireguard-secret
            - secretRef:
                name: gluetun-apikey
          volumeMounts:
            - name: gluetun-auth
              mountPath: /gluetun/auth/config-template.toml
              subPath: config-template.toml
      volumes:
        - name: gluetun-auth
          configMap:
            name: gluetun-auth
        - name: dnsdist
          configMap:
            name: dnsdist
        - name: config
          hostPath:
            path: /var/mnt/data/persistence/arr/qbittorrent/config-test
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /var/storage/media/downloads-test
            type: DirectoryOrCreate
