apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: arr
spec:
  selector:
    matchLabels:
      app: qbittorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: qbittorrentofficial/qbittorrent-nox:4.6.4-2
          env:
            - name: QBT_EULA
              value: 'true'
            - name: QBT_WEBUI_PORT
              value: '8080'
            - name: QBT_CONFIG_PATH
              value: /config
            - name: TZ
              value: Europe/Warsaw
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          hostPath:
            path: /var/openebs/local/data/arr/qbittorrent/config
            type: DirectoryOrCreate
