apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: wireguard-secret
    namespace: arr
    envs:
      - config/wireguard.env
    options:
      disableNameSuffixHash: true
  - name: gluetun-apikey
    namespace: arr
    envs:
      - config/gluetun.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: gluetun-auth
    namespace: arr
    files:
      - config.toml=config/gluetun-auth.toml
configurations:
  - kustomizeconfig.yaml
