apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: qbittorrent-values
    namespace: arr
    files:
      - values.yaml=qbittorrent-values.yaml
configurations:
  - kustomizeconfig.yaml
