apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
#  - deployment-test.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: wireguard-secret
    namespace: arr
    envs:
      - config/wireguard.env
    options:
      disableNameSuffixHash: true
  - name: gluetun-apikey
    namespace: arr
    envs:
      - config/gluetun.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: wg-conf
    namespace: arr
    files:
      - wg0-template.conf=config/wg0.conf
  - name: gluetun-auth
    namespace: arr
    files:
      - config-template.toml=config/gluetun-auth.toml
  - name: dnsdist
    namespace: arr
    files:
      - dnsdist.conf=config/dnsdist.conf
configurations:
  - kustomizeconfig.yaml
