apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
secretGenerator:
  - name: wireguard-secret
    namespace: arr
    envs:
      - wireguard.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: qbittorrent-values
    namespace: arr
    files:
      - values.yaml=qbittorrent-values.yaml
configurations:
  - kustomizeconfig.yaml
