env:
  TZ: Europe/Warsaw
  DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  PUID: 1000
  PGID: 1000

image:
  repository: ghcr.io/linuxserver/qbittorrent
  tag: version-4.6.4-r1

service:
  main:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.243
    ports:
      http:
        port: 8080

persistence:
  test:
    enabled: true
    type: hostPath
    hostPath: /var/openebs/local/data/arr/qbittorrent/test
    mountPath: /test

#persistence:
#  config:
#    enabled: true
#    existingClaim: qbittorrent-config
#  downloads:
#    enabled: true
#    existingClaim: qbittorrent-downloads
