env:
  TZ: Europe/Warsaw
  DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  PUID: 1000
  PGID: 1000
  TORRENTING_PORT: 18863

image:
  # renovate: datasource=docker depName=ghcr.io/linuxserver/qbittorrent versioning=loose
  repository: ghcr.io/linuxserver/qbittorrent
  tag: 4.6.4-r1-ls332

service:
  main:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.243
    ports:
      http:
        port: 8080
  bittorrent:
    ports:
      bittorrent:
        port: 18863
        protocol: TCP

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/openebs/local/data/arr/qbittorrent/config
    mountPath: config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /var/openebs/local/data/arr/qbittorrent/downloads
    mountPath: /downloads
  vuetorrent:
    enabled: true
    type: hostPath
    hostPath: /var/openebs/local/data/arr/qbittorrent/vuetorrent
    mountPath: /vuetorrent
