env:
  TZ: Europe/Warsaw
  DOCKER_MODS: ghcr.io/gabe565/linuxserver-mod-vuetorrent
  PUID: 1000
  PGID: 1000
  TORRENTING_PORT: 18863

image:
  # renovate: datasource=docker depName=ghcr.io/linuxserver/qbittorrent versioning=semver
  repository: ghcr.io/linuxserver/qbittorrent
  tag: 5.0.3-r0-ls379

service:
  main:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.8.243
    ports:
      http:
        port: 8080
  bittorrent:
    enabled: true
    primary: false
    nameOverride: torrent
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.8.244
    ports:
      bittorrent:
        enabled: true
        primary: false
        port: 18863
        protocol: TCP

ingress:
  main:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: 192.168.8.222
      traefik.ingress.kubernetes.io/router.entrypoints: local
    hosts:
      - host: torrent.local.boomerok.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: local-tls
        hosts:
          - torrent.local.boomerok.dev

persistence:
  config:
    enabled: true
    type: hostPath
    hostPath: /var/mnt/data/persistence/arr/qbittorrent/config
    mountPath: config
  downloads:
    enabled: true
    type: hostPath
    hostPath: /var/storage/media/downloads
    mountPath: /downloads
  vuetorrent:
    enabled: true
    type: hostPath
    hostPath: /var/mnt/data/persistence/arr/qbittorrent/vuetorrent
    mountPath: /vuetorrent
