apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: arr
spec:
  interval: 30m
  chart:
    spec:
      chart: qbittorrent
      version: 0.3.5
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: arr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: qbittorrent-values
