apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: arr
  labels:
    app.kubernetes.io/name: qbittorrent
    app: qbittorrent
spec:
  ports:
    - port: 8080
      targetPort: qbittorrent-web
      name: qbittorrent-web
  selector:
    app.kubernetes.io/name: qbittorrent
    app: qbittorrent
