apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: arr
  labels:
    app: qbittorrent
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.243
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: qbittorrent
