apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shitscreen
  namespace: shitscreen
spec:
  interval: 1m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: shitscreen
