apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  namespace: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/redis
    type: DirectoryOrCreate
