apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  labels:
    app.kubernetes.io/name: transmission
    app: transmission
spec:
  ports:
    - port: 9091
      targetPort: 9091
      name: http
  selector:
    app.kubernetes.io/name: transmission
    app: transmission
