apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - statefulset.yaml
  - service.yaml
configMapGenerator:
  - name: postgres-config
    namespace: postgres
    envs:
      - config.env
