apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-updater
  namespace: observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: geoip-updater
      app: geoip-updater
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: geoip-updater
        app: geoip-updater
    spec:
      containers:
        - name: geoip-updater
          image: ghcr.io/maxmind/geoipupdate:v7.0.1
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              value: 'GeoLite2-City GeoLite2-Country'
            - name: GEOIPUPDATE_FREQUENCY
              value: '84'
            - name: GEOIPUPDATE_PRESERVE_FILE_TIMES
              value: '1'
            - name: GEOIPUPDATE_VERBOSE
              value: '1'
            - name: GEOIPUPDATE_DB_DIR
              value: /usr/share/GeoIP
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: geoip-secrets
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: geoip-secrets
                  key: GEOIPUPDATE_LICENSE_KEY
            - name: GEOIPUPDATE_CONF_FILE
              value: /var/GeoIP.conf
          volumeMounts:
            - mountPath: /usr/share/GeoIP
              name: downloads
            - name: geoip-conf
              mountPath: /var/GeoIP.conf
              subPath: GeoIP.conf
      volumes:
        - name: geoip-conf
          secret:
            secretName: geoip-conf
        - name: downloads
          hostPath:
            path: /var/disk/a/data/observability/geoip
            type: DirectoryOrCreate
