apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
secretGenerator:
  - name: cloudflare-token
    namespace: external-dns
    envs:
      - cloudflare-token.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: external-dns-cloudflare-values
    namespace: external-dns
    files:
      - values.yaml=cloudflare-values.yaml
