apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release-cloudflare.yaml
  - release-unifi.yaml
secretGenerator:
  - name: unifi-credentials
    namespace: external-dns
    envs:
      - unifi-credentials.env
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: external-dns-unifi-values
    namespace: external-dns
    files:
      - values.yaml=unifi-values.yaml
