apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
secretGenerator:
  - name: cloudflare-token
    namespace: external-dns
    files:
      - cloudflare-token.yaml
    options:
      disableNameSuffixHash: true
