provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/kashalls/external-dns-unifi-webhook
      tag: v0.2.0
    env:
      - name: UNIFI_HOST
        value: https://192.168.1.1
      - name: UNIFI_USER
        valueFrom:
          secretKeyRef:
            name: unifi-credentials
            key: username
      - name: UNIFI_PASS
        valueFrom:
          secretKeyRef:
            name: unifi-credentials
            key: password
      - name: LOG_LEVEL
        value: debug

logLevel: debug

extraArgs:
  - --ignore-ingress-tls-spec

sources:
  - ingress
  - service

policy: sync
triggerLoopOnEvent: true
txtOwnerId: local
txtPrefix: k8s.local.

domainFilters:
  - local.boomerok.dev

serviceMonitor:
  enabled: true
