kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app: nextcloud
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/storage/nextcloud
    type: DirectoryOrCreate
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-config
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app: nextcloud
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mnt/data/persistence/nextcloud
    type: DirectoryOrCreate
