kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app: nextcloud
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app: nextcloud
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
      app: nextcloud
  resources:
    requests:
      storage: 8Gi
