apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - repository.yaml
configMapGenerator:
  - name: kubelet-csr-approver-helm-values
    namespace: kube-system
    files:
      - values.yaml=approver-values.yaml
configurations:
  - kustomizeconfig.yaml
