service:
  spec:
    loadBalancerIP: "192.168.1.200"
  additionalServices:
    internal:
      spec:
        loadBalancerIP: "192.168.1.201"
      type: LoadBalancer
      labels:
        traefik-service-label: internal
ports:
  traefik:
    expose:
      # Sensitive data should not be exposed on the internet
      # => Keep this disabled !
      default: false
      internal: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

additionalVolumeMounts:
  - name: logs
    mountPath: /var/log

deployment:
  additionalVolumes:
    - name: logs
      hostPath:
        path: /var/openebs/local/data/traefik
        type: DirectoryOrCreate

logs:
  access:
    enabled: true
    format: json
    filePath: "/var/log/access.log"
    fields:
      headers:
        defaultmode: keep
