service:
  spec:
    loadBalancerIP: "192.168.1.200"
  additionalServices:
    internal:
      spec:
        loadBalancerIP: "192.168.1.201"
      type: LoadBalancer
      labels:
        traefik-service-label: internal
ports:
#  web:
#    redirectTo:
#      port: websecure
#      scheme: https
  traefik:
    expose:
      # Sensitive data should not be exposed on the internet
      # => Keep this disabled !
      default: false
      internal: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

logs:
  general:
    format: json
  access:
    enabled: true
    format: json
    fields:
      headers:
        defaultmode: keep

additionalArguments:
#  - '--entryPoints.web.address=:8000'
  - '--entryPoints.web.http.redirections.entryPoint.to=:443'
  - '--entryPoints.web.http.redirections.entryPoint.scheme=https'
#  - '--entryPoints.websecure.address=:8443'
