apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openebs
  namespace: openebs
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
#  - storageClass.yaml
configMapGenerator:
  - name: openebs-values
    namespace: openebs
    files:
      - values.yaml=openebs-values.yaml
configurations:
  - kustomizeconfig.yaml
