engines:
  local:
    lvm:
      enabled: false
    zfs:
      enabled: true
  replicated:
    mayastor:
      enabled: false
#openebs-crds:
#  csi:
#    volumeSnapshots:
#      enabled: false
localpv-provisioner:
  hostpathClass:
    isDefaultClass: true
    basePath: /var/openebs/local
    reclaimPolicy: Retain
zfs-localpv:
  zfsNode:
    encrKeysDir: /var/zfs-keys
