- The High Seas:
    - Plex:
        href: https://plex.boomerok.dev
        icon: plex
        namespace: arr
        app: plex-media-server
        widget:
            type: plex
            url: http://plex-plex-media-server.arr:32400
            key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - Torrent:
        href: https://torrent.local.boomerok.dev
        icon: https://torrent.local.boomerok.dev/icon.svg
        namespace: arr
        app: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent.arr:8080
    - Sonarr:
        href: https://sonarr.local.boomerok.dev
        icon: sonarr
        namespace: arr
        app: sonarr
        widget:
            type: sonarr
            url: http://sonarr-service.arr:8989
            key: {{HOMEPAGE_VAR_SONARR_APIKEY}}
    - Radarr:
        href: https://radarr.local.boomerok.dev
        icon: radarr
        namespace: arr
        app: radarr
        widget:
            type: radarr
            url: http://radarr-service.arr:7878
            key: {{HOMEPAGE_VAR_RADARR_APIKEY}}
    - Bazarr:
        href: https://bazarr.local.boomerok.dev
        icon: bazarr
        namespace: arr
        app: bazarr
        widget:
            type: bazarr
            url: http://bazarr-service.arr:6767
            key: {{HOMEPAGE_VAR_BAZARR_APIKEY}}
    - Prowlarr:
        href: https://prowlarr.local.boomerok.dev
        icon: prowlarr
        namespace: arr
        app: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr-service.arr:9696
            key: {{HOMEPAGE_VAR_PROWLARR_APIKEY}}

- Infrastructure:
    - Unifi:
        href: http://192.168.1.1/network
        icon: unifi
        widget:
            type: unifi
            url: https://192.168.1.1
            username: {{HOMEPAGE_VAR_UNIFI_USER}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
