- The High Seas:
    - Plex:
        href: https://plex.boomerok.dev
        icon: plex
        namespace: arr
        app: plex-media-server
        widget:
            type: plex
            url: http://plex-plex-media-server.arr:32400
            key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - Bazarr:
        href: https://bazarr.local.boomerok.dev
        icon: bazarr
        namespace: arr
        app: bazarr
        widget:
            type: bazarr
            url: http://bazarr-service.arr:6767
            key: {{HOMEPAGE_VAR_BAZARR_APIKEY}}

- Infrastructure:
    - Unifi:
        href: http://192.168.1.1/network
        icon: unifi
        widget:
            type: unifi
            url: https://192.168.1.1
            username: {{HOMEPAGE_VAR_UNIFI_USER}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
