- The High Seas:
    - Plex:
        href: https://plex.boomerok.dev
        icon: plex
        widget:
            type: plex
            url: plex-plex-media-server.arr
            port: 32400
            key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - Bazarr:
        href: https://bazarr.local.boomerok.dev
        icon: bazarr
        widget:
            type: bazarr
            url: bazarr-service.arr
            port: 6767
            key: {{HOMEPAGE_VAR_BAZARR_APIKEY}}

- Infrastructure:
    - Unifi:
        href: 192.168.1.1
        icon: unifi
        widget:
            type: unifi
            url: https://192.168.1.1
            username: {{HOMEPAGE_VAR_UNIFI_USER}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
