- My First Group:
    - Plex:
        href: https://plex.boomerok.dev
        icon: plex
        widget:
            type: plex
            url: https://plex.boomerok.dev:443
            key: {{HOMEPAGE_VAR_PLEX_TOKEN}}

    - My First Service:
        href: http://localhost/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
