- kubernetes:
    cluster:
      show: false
      cpu: true
      memory: true
      showLabel: true
      label: homelab
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
- unifi_console:
    url: https://192.168.1.1
    username: {{HOMEPAGE_VAR_UNIFI_USER}}
    password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    locale: iso
    format:
      dateStyle: short
      timeStyle: medium
      hourCycle: h23
