- kubernetes:
    cluster:
      show: false
      cpu: true
      memory: true
      showLabel: true
      label: homelab
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
- resources:
    label: Storage
    disk:
      - /mnt/a
      - /mnt/b
- unifi_console:
    url: https://192.168.1.1
    username: {{HOMEPAGE_VAR_UNIFI_USER}}
    password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
- openmeteo:
    label: Bielsko-Biała
    latitude: 49.822081055681224
    longitude: 19.026997039793688
    timezone: Europe/Warsaw
    units: metric
    cache: 5 # minutes
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- datetime:
    locale: iso
    format:
      dateStyle: short
      timeStyle: medium
      hourCycle: h23
- search:
    provider: duckduckgo
    target: _blank
