- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: homelab
    nodes:
      show: false
      cpu: true
      memory: true
      showLabel: true
- resources:
    backend: resources
    expanded: true
    cpu: true
    memory: true
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    format:
      dateStyle: short
      timeStyle: medium
      hourCycle: h23
