apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: arr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radarr
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.7.0
          ports:
            - name: radarr
              containerPort: 7878
          env:
            - name: TZ
              value: Europe/Warsaw
            - name: PUID
              value: '1000'
            - name: GUID
              value: '1000'
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data/movies
              name: movies
            - mountPath: /data/downloads
              name: downloads
      volumes:
        - name: config
          hostPath:
            path: /var/disk/a/data/arr/radarr
            type: DirectoryOrCreate
        - name: movies
          hostPath:
            path: /var/disk/a/media/video/movies
            type: DirectoryOrCreate
        - name: downloads
          hostPath:
            path: /var/disk/a/data/arr/qbittorrent/downloads
            type: DirectoryOrCreate
