apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: arr
  labels:
    app.kubernetes.io/name: radarr
    app: radarr
spec:
  ports:
    - port: 7878
      targetPort: radarr
      name: radarr
  selector:
    app.kubernetes.io/name: radarr
    app: radarr
