apiVersion: v1
kind: Pod
metadata:
  name: zfs-setup-pod
  namespace: zfs
spec:
  containers:
    - name: zfs-setup
      image: ubuntu:20.04
      securityContext:
        privileged: true
      command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y zfsutils-linux ; sleep 3600 && \
          tail -f /dev/null
      volumeMounts:
        - name: device-dir
          mountPath: /dev
  volumes:
    - name: device-dir
      hostPath:
        path: /dev
  hostIPC: true
  hostPID: true
