apiVersion: v1
kind: Pod
metadata:
  name: zfs-setup-pod
  namespace: zfs
spec:
  containers:
    - name: zfs-setup
      image: ubuntu:24.04
      securityContext:
        privileged: true
      command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y zfsutils-linux curl git zsh && \
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
          tail -f /dev/null
      volumeMounts:
        - name: device-dir
          mountPath: /dev
        - name: var-mnt
          mountPath: /var/mnt
        - name: var-disk
          mountPath: /var/disk
        - name: var-persistence
          mountPath: /var/persistence
  volumes:
    - name: device-dir
      hostPath:
        path: /dev
    - name: var-mnt
      hostPath:
        path: /var/mnt
    - name: var-disk
      hostPath:
        path: /var/disk
    - name: var-persistence
      hostPath:
        path: /var/persistence
        type: DirectoryOrCreate
  hostIPC: true
  hostPID: true
