apiVersion: v1
kind: Pod
metadata:
  name: zfs-setup-pod
  namespace: zfs
spec:
  containers:
    - name: zfs-setup
      image: ubuntu:24.04
      securityContext:
        privileged: true
      command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y zfsutils-linux curl git zsh && \
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
          tail -f /dev/null
      volumeMounts:
        - name: device-dir
          mountPath: /opt/dev
        - name: host-run
          mountPath: /opt/run
        - name: host-var
          mountPath: /opt/var
  volumes:
    - name: host-var
      hostPath:
        path: /var
    - name: device-dir
      hostPath:
        path: /dev
    - name: host-run
      hostPath:
        path: /run
  hostIPC: true
  hostPID: true
