apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: arr
  labels:
    app: plex-media-server
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex-media-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.boomerok.dev`) && PathPrefix(`/outpost.goauthentik.io/`)
      kind: Rule
      priority: 10
      middlewares:
        - name: redirect-https
          namespace: traefik
      services:
        - name: authentik-server
          namespace: authentik
          port: 80
    - match: Host(`plex.boomerok.dev`) && PathPrefix(`/`)
      kind: Rule
      priority: 5
      middlewares:
        - name: redirect-https
          namespace: traefik
      services:
        - name: plex-plex-media-server
          port: 32400
  tls:
    secretName: plex-tls
