apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv.yaml
  - pvc.yaml
  - repository.yaml
  - release.yaml
  - gluetun.yaml
  - wireguard.yaml
configMapGenerator:
  - name: plex-values
    namespace: arr
    files:
      - values.yaml=plex-values.yaml
configurations:
  - kustomizeconfig.yaml
