image:
  # renovate: datasource=docker depName=plexinc/pms-docker versioning=loose
  repository: plexinc/pms-docker
  tag: 1.41.4.9463-630c9f557

pms:
  configExistingClaim: plex-config

extraEnv:
  TZ: Europe/Warsaw

extraVolumeMounts:
  - mountPath: /media/video
    name: video
    readOnly: true

extraVolumes:
  - name: video
    hostPath:
      path: /var/storage/media/video
      type: DirectoryOrCreate

ingress:
  enabled: true
  ingressClassName: traefik
  url: https://plex.boomerok.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: LoadBalancer
  port: 32400
  annotations:
    io.cilium/lb-ipam-ips: 100.104.23.110
