image:
  # renovate: datasource=docker depName=plexinc/pms-docker versioning=loose
  repository: plexinc/pms-docker
  tag: 1.40.3.8555-fef15d30c

pms:
  configExistingClaim: plex-config

extraEnv:
  TZ: Europe/Warsaw

extraVolumeMounts:
  - mountPath: /media/video
    name: video
    readOnly: true

extraVolumes:
  - name: video
    hostPath:
      path: /var/mnt/data/media/video
      type: Directory

ingress:
  enabled: true
  ingressClassName: traefik
  url: https://plex.boomerok.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 32400
  annotations: {}
