image:
  # renovate: datasource=docker depName=plexinc/pms-docker versioning=loose
  repository: plexinc/pms-docker
  tag: 1.40.3.8555-fef15d30c

pms:
  configExistingClaim: plex-config

extraEnv:
  TZ: Europe/Warsaw
  PLEX_UID: '1043'
  PLEX_GUID: '1043'

extraVolumeMounts:
  - mountPath: /seriale
    name: series

extraVolumes:
  - name: series
    hostPath:
      path: /var/openebs/local/media/video/series
      type: DirectoryOrCreate

ingress:
  enabled: true
  ingressClassName: traefik
  url: https://plex.boomerok.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 32400
  annotations: {}
