image:
  # renovate: datasource=docker depName=plexinc/pms-docker versioning=loose
  repository: plexinc/pms-docker
  tag: 1.40.3.8555-fef15d30c

pms:
  configExistingClaim: plex-config

extraEnv:
  TZ: Europe/Warsaw

extraVolumeMounts:
  - mountPath: /seriale
    name: series
  - mountPath: /series
    name: series
  - mountPath: /filmy
    name: movies
  - mountPath: /movies
    name: movies
  - mountPath: /anime
    name: anime
  - mountPath: /bleach
    name: bleach

extraVolumes:
  - name: series
    hostPath:
      path: /var/disk/a/media/video/series
      type: DirectoryOrCreate
  - name: movies
    hostPath:
      path: /var/disk/a/media/video/movies
      type: DirectoryOrCreate
  - name: anime
    hostPath:
      path: /var/disk/a/media/video/anime
      type: DirectoryOrCreate
  - name: bleach
    hostPath:
      path: /var/disk/a/media/video/bleach
      type: DirectoryOrCreate

ingress:
  enabled: true
  ingressClassName: traefik
  url: https://plex.boomerok.dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 32400
  annotations: {}
