apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  namespace: arr
  labels:
    app.kubernetes.io/name: plex
    app: plex
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/data/persistence/arr/plex
    type: DirectoryOrCreate
