apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: arr
  labels:
    app.kubernetes.io/name: plex
    app: plex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
      app: plex
