apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: arr
spec:
  interval: 30m
  chart:
    spec:
      chart: plex-media-server
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: plex
        namespace: arr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: plex-values
