apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: v7.1.262
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: reflector
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
