apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: leantime
  namespace: leantime
spec:
  interval: 30m
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: leantime
        namespace: leantime
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: leantime-values
