apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: leantime
  namespace: leantime
spec:
  interval: 12h
  url: https://raw.githubusercontent.com/Leantime/leantime/master/helm
