apiVersion: v1
kind: Secret
metadata:
  name: leantime-secrets
  namespace: leantime
type: Opaque
stringData:
  mariadb-root-password: 'yjuy0dy9u75gfwwayjf87'
  mariadb-replication-password: ''
  mariadb-password: 'y272a1u1hjz2n436rd5as'
