apiVersion: apps/v1
kind: Deployment
metadata:
  name: isponsorblocktv
  namespace: isponsorblocktv
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: isponsorblocktv
      app: isponsorblocktv
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: isponsorblocktv
        app: isponsorblocktv
    spec:
      containers:
        - name: isponsorblocktv
          image: ghcr.io/dmunozv04/isponsorblocktv:v2.1.0
          volumeMounts:
            - mountPath: /app/data
              name: config
      volumes:
        - name: config
          secret:
            secretName: isponsorblocktv-config
