apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
configMapGenerator:
  - name: isponsorblocktv-config
    namespace: isponsorblocktv
    files:
      - config.json
configurations:
  - kustomizeconfig.yaml
