apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarizer
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diarizer
  template:
    metadata:
      labels:
        app: diarizer
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: diarizer
          image: ghcr.io/marcin795/processing-diarizer:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbit-credentials
            - secretRef:
                name: huggingface-token
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /var/storage/processing/data
            type: DirectoryOrCreate
