apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: shitscreen
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node
        app: node
    spec:
      containers:
        - name: node
          command:
            - tail
            - -f
            - /dev/null
          image: node
          volumeMounts:
            - mountPath: /node
              name: node
      volumes:
        - name: node
          hostPath:
            path: /var/disk/a/node
            type: DirectoryOrCreate
