# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

input_select:
  salon_scene_state:
    name: Salon Scene State
    options:
      - "off"
      - "white"
      - "pink"
    initial: "off"

template:
  - binary_sensor:
      - name: "Salon White Active"
        state: >
          {{ is_state('input_select.salon_scene_state', 'white') }}
        icon: mdi:lightbulb-on

      - name: "Salon Pink Active"
        state: >
          {{ is_state('input_select.salon_scene_state', 'pink') }}
        icon: mdi:lightbulb-on-outline
