apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: arr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
      app: tautulli
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
        app: tautulli
    spec:
      containers:
        - name: tautulli
          image: linuxserver/tautulli:v2.14.3-ls144
          ports:
            - name: tautulli
              containerPort: 8181
          env:
            - name: TZ
              value: Europe/Warsaw
            - name: PUID
              value: '1000'
            - name: GUID
              value: '1000'
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          hostPath:
            path: /var/mnt/data/persistence/arr/tautulli
            type: DirectoryOrCreate
