apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
  namespace: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: downloader
          image: ghcr.io/marcin795/processing-downloader:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: rabbit-credentials
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /var/storage/processing/data
            type: DirectoryOrCreate
