apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - enp3s0
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
