apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: l7-visibility
  namespace: authentik
spec:
  endpointSelector:
    matchLabels:
      app: authentik
  egress:
    - toEndpoints:
        - matchLabels:
            app: authentik
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "9000"
              protocol: TCP
            - port: "6379"
              protocol: TCP
            - port: "5432"
              protocol: TCP
          rules:
            http: [{}]
