apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: authentik
spec:
  description: "Allow all traffic in both directions on all ports for both TCP and UDP"
  endpointSelector:
    matchLabels:
      app: authentik
  ingress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "9000"
              protocol: TCP
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
              - method: POST
  egress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "9000"
              protocol: TCP
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
              - method: POST
