apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: authentik
spec:
  description: "Allow all traffic in both directions on all ports for both TCP and UDP"
  endpointSelector:
    matchLabels: {}
  ingress:
    - toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
          rules:
            http:
              - method: GET
              - method: POST
              - method: PUT
              - method: DELETE
  egress:
    - toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
