apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: authentik
spec:
  description: "Allow all traffic in both directions on all ports for both TCP and UDP"
  endpointSelector:
    matchLabels:
      any: []
  ingress:
    - toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
  egress:
    - toPorts:
        - ports:
            - port: "0"
              protocol: TCP
            - port: "0"
              protocol: UDP
