apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-all-traffic
  namespace: authentik
spec:
  description: "Allow all traffic in both directions on all ports for both TCP and UDP"
  endpointSelector:
    matchLabels: {}
#      app: authentik
  ingress:
    - toPorts:
      - ports:
        - port: '9000'
          protocol: TCP
        rules:
          http:
            - host: boomerok.dev
            - host: authentik.boomerok.dev
  egress:
    - toPorts:
      - ports:
        - port: '443'
          protocol: ANY
      - ports:
        - port: '53'
          protocol: ANY
      - ports:
        - port: '5432'
          protocol: TCP
      - ports:
        - port: '6379'
          protocol: TCP
#    - toServices:
#        - k8sService:
#            serviceName: postgres-service
#            namespace: postgres
#---
#apiVersion: cilium.io/v2
#kind: CiliumNetworkPolicy
#metadata:
#  name: postgres-policy
#  namespace: postgres
#spec:
#  endpointSelector:
#    matchLabels: {}
##      app: postgres
#  ingress:
#    - toPorts:
#      - ports:
#        - port: '5432'
#          protocol: TCP
