apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: arr
  labels:
    app.kubernetes.io/name: plex
    app: plex
spec:
  ports:
    - port: 32400
      targetPort: 32400
      name: http
  selector:
    app.kubernetes.io/name: plex
    app: plex
---
apiVersion: v1
kind: Service
metadata:
  name: plex-32400
  namespace: arr
  labels:
    app.kubernetes.io/name: plex
    app: plex
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.202
spec:
  ports:
    - port: 32400
      targetPort: 32400
      name: http
  selector:
    app.kubernetes.io/name: plex
    app: plex
  type: LoadBalancer
