apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: observability
  labels:
    app: alertmanager
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/alertmanager
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: observability
  labels:
    app: grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/grafana
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: observability
  labels:
    app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/prometheus
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: observability
  labels:
    app: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/observability/loki/storage
    type: DirectoryOrCreate
