apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: arr
  labels:
    app.kubernetes.io/name: sonarr
    app: sonarr
spec:
  ports:
    - port: 8989
      targetPort: sonarr
      name: sonarr
  selector:
    app.kubernetes.io/name: sonarr
    app: sonarr
