apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
  namespace: arr
  labels:
    app: plex
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/openebs/local/data/arr/plex
    type: DirectoryOrCreate
