apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: arr
  labels:
    app: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: plex
