apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app: home-assistant
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant
        app: home-assistant
    spec:
      hostNetwork: true
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          ports:
            - containerPort: 8123
              name: home-assistant
          env:
            - name: TZ
              value: Europe/Warsaw
          volumeMounts:
            - mountPath: /config
              name: config
#            - mountPath: /config/configuration.yaml
#              subPath: configuration.yaml
#              name: configuration-yaml
#            - mountPath: /config/automations.yaml
#              subPath: automations.yaml
#              name: automations-yaml
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: configuration-yaml
          configMap:
            name: configuration-yaml
        - name: automations-yaml
          configMap:
            name: automations-yaml
