apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pv.yaml
  - pvc.yaml
configMapGenerator:
  - name: configuration-yaml
    namespace: home-assistant
    files:
      - configuration.yaml=config/configuration.yaml
