kind: PersistentVolume
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mnt/data/persistence/home-assistant/config
    type: DirectoryOrCreate
