kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app: home-assistant
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app: home-assistant
  resources:
    requests:
      storage: 1Gi
