apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rabbit
  - ingest
  - download
  - database
  - audio-extractor
secretGenerator:
  - name: rabbit-credentials
    namespace: processing
    envs:
      - rabbit.env
    options:
      disableNameSuffixHash: true
  - name: postgres-credentials
    namespace: processing
    envs:
      - postgres.env
    options:
      disableNameSuffixHash: true
