apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-data
  namespace: processing
  labels:
    app.kubernetes.io/name: rabbit
    app: rabbit
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbit
      app: rabbit
