apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbit
  namespace: processing
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq
      version: 15.3.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: processing
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: rabbit-values
