apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
configMapGenerator:
  - name: grafana-loki-values
    namespace: observability
    files:
      - values.yaml=loki-values.yaml
configurations:
  - ../kustomizeconfig.yaml
