deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumeMounts:
    - mountPath: /var/loki
      name: data
  extraVolumes:
    - name: data
      hostPath:
        path: /var/openebs/local/data/observability/loki
        type: DirectoryOrCreate

gateway:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: gateway
          topologyKey: kubernetes.io/hostname

read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
