apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: combined-middleware
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: redirect-https
      - name: authentik-middleware
