apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - combined-middleware.yaml
  - tls-option.yaml
  - traefik-auth-middleware.yaml
  - traefik-https-redirect-middleware.yaml
