apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: openebs
  namespace: openebs
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
configMapGenerator:
  - name: openebs-values
    namespace: openebs
    files:
      - values.yaml=openebs-values.yaml
configurations:
  - kustomizeconfig.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 10m0s
  path: ./kubernetes/infra/controller/openebs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
