{
 "title": "Traefik Dashboard",
 "description": "Traefik access logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connection origins",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} |= `RequestProtocol` | json ClientAddr, ClientHost, DownstreamStatus, OriginStatus, RequestAddr, RequestHost, RequestMethod, RequestPath, RequestPort, RequestProtocol, RequestScheme, geoip_location_latitude, geoip_location_longitude, request_X_Forwarded_Host=`[\"request_X-Forwarded-Host\"]`, request_X_Forwarded_Port=`[\"request_X-Forwarded-Port\"]`, request_X_Forwarded_Proto=`[\"request_X-Forwarded-Proto\"]`, request_X_Forwarded_For=`[\"request_X-Forwarded-For\"]`, CloudflareIp=`[\"request_X-Real-Ip\"]`, time, RouterName, ServiceName, TLSVersion, request_Cf_Connecting_Ip=`[\"request_Cf-Connecting-Ip\"]`\n | __error__=`` | drop app,container, filename, instance, job, namespace, node_name, pod, service_name, geoip_continent_code, geoip_continent_name, geoip_timezone, stream, geoip_country_name, geoip_city_name, level"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "<div class=\"left dashboard-header\">\n   <img src=\"https://marketplace-assets.digitalocean.com/logos/loki-logo.svg\" style=\"height:29px;\"/>\n  <span>Traefik Dashboard</span>\n</div>"
   },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | __error__=`` [$__interval]))"
    }
   ]
  },
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (count_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" | json |  __error__=\"\" [$__interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 0 | DownstreamStatus < 100 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 0"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 100 | DownstreamStatus < 200 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 1XX"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 200 | DownstreamStatus < 300 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 2XX"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 300 | DownstreamStatus < 400 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 3XX"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 400 | DownstreamStatus < 500 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 4XX"
    },
    {
     "expr": "sum(count_over_time({namespace=\"traefik\"} |= `RequestProtocol` | json | DownstreamStatus >= 500 | DownstreamStatus < 600 | __error__=`` [$__interval]))",
     "legendFormat": "HTTP Status: 5XX"
    }
   ]
  },
  {
   "title": "% of  4/5xx ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " sum(rate({namespace=\"traefik\"} |~ \"RequestProtocol\" | json | DownstreamStatus >= 400 |__error__=\"\"[$__interval])) / (sum(rate({namespace=\"traefik\"} |~ \"RequestProtocol\" | json | __error__=\"\"[$__interval])) / 100)"
    }
   ]
  },
  {
   "title": " 4/5xx  Services",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (DownstreamStatus,ServiceName) (count_over_time({namespace=\"traefik\"} |~ \"RequestProtocol\" | json | DownstreamStatus >= 400 |__error__=\"\"[$__interval]))",
     "legendFormat": " {{ServiceName}} / {{DownstreamStatus}} "
    }
   ]
  },
  {
   "title": "Clients over 30m",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count(sum by (ClientHost) (count_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" | json |  __error__=\"\" [$__interval])))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" | json | DownstreamStatus=200 | unwrap DownstreamContentSize |  __error__=\"\" [$__interval])",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Requests Route",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (RouterName) (\n  label_replace(\n    count_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" | json | __error__=\"\" [$__interval]),\n    \"RouterName\",\n    \"Miss\",\n    \"RouterName\",\n    \"\"\n  )\n)",
     "legendFormat": "{{RouterName}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"traefik\"} |= `RequestProtocol` | json | __error__=`` | line_format `Status:{{.DownstreamStatus}} Client From {{if .request_Cf_Connecting_Ip}}{{.request_Cf_Connecting_Ip}}{{else}}{{.ClientHost}}{{end}} {{.RequestMethod}} {{.RequestAddr}}{{.RequestPath}} Route To {{.ServiceAddr}}`"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(ClientHost) (count_over_time({namespace=\"traefik\"} |= `ClientHost` | json | __error__=`` | line_format `{{.ClientHost}}` [$__auto]))",
     "legendFormat": "{{ClientHost}}"
    }
   ]
  },
  {
   "title": "95th percentile of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "quantile_over_time(0.95,{namespace=\"traefik\"} |= \"RequestProtocol\"| json | unwrap Duration |  __error__=\"\"  [$__interval]) by (ServiceName)",
     "legendFormat": " {{ ServiceName }}"
    }
   ]
  },
  {
   "title": "Max Age of Request Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (ServiceName) (max_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" |json | unwrap Duration |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ ServiceName}}"
    }
   ]
  },
  {
   "title": "Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (ServiceName) (sum_over_time({namespace=\"traefik\"} |= \"RequestProtocol\" |json | unwrap RequestContentSize |  __error__=\"\"  [$__interval]))",
     "legendFormat": "{{ ServiceName}}"
    }
   ]
  }
 ]
}