apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: arr
  labels:
    app: prowlarr
spec:
  ports:
    - port: 9696
      targetPort: prowlarr
      name: prowlarr
  selector:
    app: prowlarr
