apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - arr
  - homepage
  - isponsorblocktv
  - home-assistant
  - mosquitto
  - storage/scratch.yaml
  - nextcloud
  - processing
  - leantime
