apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: observability
spec:
  interval: 12h
  url: https://kubernetes-sigs.github.io/metrics-server/
