apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app: postgres
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.205
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-tailscale
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app: postgres
  annotations:
    io.cilium/lb-ipam-ips: 100.104.23.110
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres
  labels:
    app.kubernetes.io/name: postgres
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgres
    app: postgres
