apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-pods
  namespace: kube-system
spec:
  schedule: "0/15 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl delete pod --field-selector=status.phase==Succeeded --all-namespaces
                  kubectl delete pod --field-selector=status.phase==Failed --all-namespaces
          restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cleanup-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleanup-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io
