alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app: alertmanager

grafana:
  service:
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: 192.168.1.230
  persistence:
    enabled: true
    existingClaim: grafana-pvc
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://grafana-loki.observability:3100/

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
          selector:
            matchLabels:
              app: prometheus
