apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - volumes/pv.yaml
  - volumes/pvc.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: observability
    files:
      - values.yaml=kube-prometheus-stack-values.yaml
  - name: grafana-loki-values
    namespace: observability
    files:
      - values.yaml=grafana-loki-values.yaml
configurations:
  - kustomizeconfig.yaml
