apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 60.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: loki
      version: 6.6.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: grafana-loki-values
