apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - letsencrypt-prod.yaml
  - local-certificate.yaml
secretGenerator:
  - name: cloudflare-token
    namespace: cert-manager
    envs:
      - cloudflare-token.env
    options:
      disableNameSuffixHash: true
