apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: szalabskim@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: apiToken
        selector:
          dnsZones:
            - boomerok.dev
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-token
              key: apiToken
        selector:
          dnsZones:
            - local.boomerok.dev
