apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: redis-password
    namespace: redis
    files:
      - redis-password.yaml
    options:
      disableNameSuffixHash: true
configMapGenerator:
  - name: redis-values
    namespace: redis
    files:
      - values.yaml=redis-values.yaml
configurations:
  - kustomizeconfig.yaml
